### ISSUE TITLE
Dokončení designu pro filtrovací stránky

### ISSUE THREAD

**Issue by VojtaCodeMaster** [mickova/Projekt_Pandik#129]
# Dokončení designu pro filtrovací stránky

### Úkoly
- [x] přidat footer
- [x] upravit pozadí stránky (jiná barva, možná nějaký design element/obrázek)
- [x] upravit nadpis Předfmětu (font, velikost, pozice)

**Comment by mickova** [comment]
Netřeba uporavovat
