### ISSUE TITLE
Test hlavní stránky

### ISSUE THREAD

**Issue by MLorenz04** [mickova/Projekt_Pandik#19]
# Test hlavní stránky

### Úkoly
- [x] Otestovat hlavní stránku
- [x] Otestovat funkčnost linků na přihlášení a registraci

**Comment by HammerH0ld** [comment]
# Zahajeni testovani

- hlavní stránka je funkční, zobrazuje se nadpis Homepage + linky Profil a Nastaveni

- funkčnost linků na přihlášení a registraci byla úspěšně otestována. Funkčnost těchto linků byla ověřena a linky 
splňují svoji funkci.

**Comment by HammerH0ld** [comment]
# Délka práce
- 15 min
