### ISSUE TITLE
Test nastavení

### ISSUE THREAD

**Issue by MLorenz04** [mickova/Projekt_Pandik#20]
# Otestovat nastavení

### Úkoly

- [x] Zkontrolovat funkčnost nastavení
- [x] Otestování inputů hesla
- [x] Otestování inputů jména

**Comment by HammerH0ld** [comment]
#Zahajeni testovani

- přechod z hlavní stránka do nastavení funguje
- stránka nastavení je funkční
- input hesla byl otestován a je funkční
- input jména byl otestován a je funkční

#Délka práce

- 20 min
