### ISSUE TITLE
Test přihlášení

### ISSUE THREAD

**Issue by MLorenz04** [mickova/Projekt_Pandik#21]
# Otestování, zdali se může uživatel úspěšně přihlásit

### Úkoly
- [x] Test přihlášení se správnými údaji
- [x] Test přihlášení se správným heslem, ale špatným emailem
- [x] Test přihlášení se správným emailem, ale špatným heslem
- [x] Test přihlášení se špatnými údaji

**Comment by HammerH0ld** [comment]
# Zahajeni testovani

- Test přihlášení se správnými údaji proběhl úspěšně, uživatel se přihlásil do systému.

-  Test přihlášení se správným heslem, ale špatným emailem proběhl neúspěšně. Program správně zareagoval na špatně zadaný email, bude nutné přidat chybovou hlášku o špatném emailu.

-  Test přihlášení se správným emailem, ale špatným heslem proběhl neúspěšně. Program správně zareagoval na špatně zadanýheslo, bude nutné přidat chybovou hlášku o špatném heslu.

-  Test přihlášení se špatnými údaji proběhl neúspěšně. Program správně zareagoval na špatně zadaný email a heslo, bude nutné přidat chybovou hlášku o špatném emailu a heslu.

# Délka práce

- 20 min
