### ISSUE TITLE
Test úvodní stránky

### ISSUE THREAD

**Issue by MLorenz04** [mickova/Projekt_Pandik#23]
# Otestovat funkčnost úvodní stránky

### Úkoly
- [x] Otestovat, jestli fungují odkazy na přihlášení
- [x] Otestovat, jestli fungují odkazy na registraci
- [x] Otestovat, jestli obsahuje design a popis projektu

**Comment by HammerH0ld** [comment]
# Zahajeni testovani

- Odkaz na přihlášení je plně funkční.

- Odkaz na registraci není funkční, nutné dodělat
- Úvodní stránka neobsahuje design a popis projektu, nutné dodělat
# Délka práce

- 5 min

**Comment by HammerH0ld** [comment]
# Dokončení testování
- Odkaz na přihlášení byl otestován.

- Odkaz na registraci je funkční.

- Úvodní stránka obsahuje design a popis projektu.

# Délka práce
- 8 min
