### ISSUE TITLE
Test registrace

### ISSUE THREAD

**Issue by MLorenz04** [mickova/Projekt_Pandik#24]
# Testování registrace

### Úkoly
- [x] Otestovat, zdali se uživatel může úspěšně registrovat
- [x] Otestovat, zdali se uživatel následně přihlásí
- [x] Otestovat duplicitní jména, hesla mohou být

**Comment by HammerH0ld** [comment]
# Zahájení testování
- Uživatel se může jednoduše registrovat
- Uživatel se může přihlásit
- Není ošetřeno duplicitní jméno, nutné dodělat
# Doba práce
- 15

**Comment by HammerH0ld** [comment]
# Dokončení testování
- Duplicitní jména fungují

# Doba práce
- 15 min
