### ISSUE TITLE
Test profilu

### ISSUE THREAD

**Issue by MLorenz04** [mickova/Projekt_Pandik#26]
# Testování profilu a tahání dat z DB
### Úkoly
- [x] Otestovat, jestli se profil správně načítá
- [x] Otestovat správnost údajů
- [x] Otestovat všechny prokliky na linky

**Comment by HammerH0ld** [comment]
# Zahájení testování
- Po testování se profil správně načítá
- Údaje jsou správné
- Všechny prokliky na linky fungují

# Délka práce
- 10 min
