### ISSUE TITLE
Test nápovědy

### ISSUE THREAD

**Issue by MLorenz04** [mickova/Projekt_Pandik#31]
# Testing stránky nápovědy

### Úkoly
- [x] Kontrola, zdali textace sedí
- [x] Kontrola, jestli linky odkazují tam, kam mají

**Comment by HammerH0ld** [comment]
# Zahájení testování
- textace sedí
- na stránce nápověda se nic nezobrazuje, linky nikam neodkazují, nutné dodělat

# Délka práce
- 5 min
