### ISSUE TITLE
Vytvoření celkového designu stránky nápovědy

### ISSUE THREAD

**Issue by MLorenz04** [mickova/Projekt_Pandik#40]
# Vytvoření celkového designu stránky nápovědy
### Úkoly
- [x] Podle wireframe vytvořit celkový návrh designu
- [x] Kódy barev, velikosti odrážek, velikost fontů, marginů, paddinů, všechny detaily prosím.

**Comment by VojtaCodeMaster** [comment]
Stránka byla vytvořena a nadesignována podle předlohy wireframu a po schválení vrchního designéra.
