### ISSUE TITLE
Test přidání materiálu

### ISSUE THREAD

**Issue by MLorenz04** [mickova/Projekt_Pandik#41]
# Testování přidání materiálu
### Úkoly
- [x] Vyzkoušet přidat materiál
- [x] Vyzkoušet různé typy inputů, nepokoušet shodit stránku, bezpečnost budu řešit jako poslední
- [x] Vyzkoušet všechny odkazy a linky
- [x] Vyzkoušet upravit materiál
- [x] Vyzkoušet zobrazit jednotlivý materiál
- [x] Vyzkoušet různé filtrování materiálu

**Comment by HammerH0ld** [comment]
# Zahájení testování
- Přidání materiálu funguje.
- Při přidání špatného materiálu se správně nepřidá.
- Všechny odkazy a linky fungují, jedinou vyjimkou je získání materiálu na tlačítku: **zde**
- Úprava materiálu funguje
- Zobrazení jednotlivého materiálu nefunguje, nutné dodělat
- Různé filtrování materiálu funguje

# Délka práce
- 20 min
